common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  password:

development:
  <<: *common
  database: restauranteur_development

test:
  <<: *common
  database: restauranteur_test

production:
  <<: *common
  database: restauranteur_production
